### PR TITLE
Fix certbot authentication on Debian with Apache and NGINX

### PR DESCRIPTION
**Pull request by Talkless**
~~Add python-certbot-apache package to enable Certbot apache plugin.~~
Add relevant packages to enable Certbot plugins fo Apache and NGINX web servers.

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by Talkless** [comment]
True, so maybe map.jinja is not the place to do that logic? 

`map.jinja` could define `pkgs_apache` and `pkgs_nginx`, and then `client/init.sls` should use these variables if `apache` or `nginx` auth is used, right?

**Comment by fpytloun** [comment]
Yes, that would be best.

**Comment by Talkless** [comment]
@fpytloun Could you re-review this review? :-) 
I've pushed updated commit.

**Comment by fpytloun** [comment]
Nice, thank you :-)

**Comment by Talkless** [comment]
@fpytloun any idea why GitHub does not show me the "Delete branch" button in this PR?

**Comment by fpytloun** [comment]
It will probably show it only if you created branch in upstream repo (salt-formulas/salt-formula-letsencrypt) and not in your fork.

**Pull request merged**
